name: release
on: [push]

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd website
          yarn install --dev

      - name: Build project
        run: |
          cd website
          yarn build
          touch build/.nojekyll

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/build
          CLEAN: true
